name = 'Lanyon'
license = 'MIT'
licenselink = 'https://github.com/ItachiSan/hugo-theme-lanyon/LICENSE.md'
description = "A port of Jekyll's Lanyon theme, with a few extra goodies."

# The home page of the theme, where the source can be found
homepage = 'https://github.com/ItachiSan/hugo-theme-lanyon'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'minimal', 'responsive', 'personal']
features = ['disqus', 'analytics']

# If the theme has a single author
[author]
name = 'Giovanni Santini'
homepage = 'https://giovanni.is-a.dev'

# If porting an existing theme
[original]
author = 'Mark Otto'
homepage = 'https://markdotto.com/'
repo = 'https://github.com/poole/lanyon'
